### ISSUE TITLE
Help to run it on my local?

### ISSUE THREAD

**Issue by chicodelacruz** [EricEchemane/OpenAI-Completer#3]
Hi eric, can you please help me to run this one on my local?
![Screenshot at Mar 29 15-27-06](https://user-images.githubusercontent.com/28640114/160557109-7f5380da-7e4d-417b-8fe9-e5ad31c2c8fc.png)

**Comment by EricEchemane** [comment]
You did it right, unfortunately my backend code is completely separated. You need to run it also to test locally.

[backend heres the repo](https://github.com/EricEchemane/SERVER-EEs-OpenAI-Completer)

in `index.js` , remove line 22.

then create `.env` file and append a variable `OPENAI_API_KEY` equal to your openai API key.

**Comment by chicodelacruz** [comment]
Will try this one, thanks.

**Comment by chicodelacruz** [comment]
Hi Eric,

Is my structure correct? sorry I'm new on node.
![Screenshot at Mar 29 19-50-46](https://user-images.githubusercontent.com/28640114/160605176-0f4c1125-c4d0-4e8d-b5e2-4ddd84855313.png)
![Screenshot at Mar 29 19-51-11](https://user-images.githubusercontent.com/28640114/160605189-48751f29-be73-4f96-be99-2bfa0136b88c.png)
![Screenshot at Mar 29 19-51-23](https://user-images.githubusercontent.com/28640114/160605192-ba5ccf83-9c37-45ed-8ffa-c3d7c01b5f20.png)

**Comment by EricEchemane** [comment]
In the frontend, `src/App.svelte` replace `line: 53` with your local server url. 

Example:  `http://localhost:3000/complete`

**Comment by EricEchemane** [comment]
Remember to run your frontend and backend server using `npm run dev`
